AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  MyLambdaLiz:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: upb-lambda
      Handler: app.lambda_handler
      Runtime: python3.7
      CodeUri: s3://lizdeployments/b10235d7700623fdbaa45c426107a7b9
      Policies:
      - S3ReadPolicy:
          BucketName: lizdeployments
      - CloudWatchAgentAdminPolicy
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - s3:ListAllMyBuckets
          Resource: '*'
